terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }

  required_version = "~> 1.0"
}

provider "aws" {
  region = "us-east-1"
  
  default_tags {
    tags = {
    provisioner = "terraform"
   }
 }
}

locals { 
  repositories = { 
    "rancher/backup-restore-operator" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/calico-cni" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/cis-operator" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/coreos-kube-state-metrics" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/coreos-prometheus-config-reloader" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/coreos-prometheus-operator" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/externalip-webhook" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/flannel-cni" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/fleet-agent" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/fleet" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/gitjob" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/grafana-grafana" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-calico" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-calico" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-calico" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-cluster-autoscaler" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-cluster-autoscaler" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-cni-plugins" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-cni-plugins" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-coredns" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-coredns" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-dns-node-cache" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-dns-node-cache" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-etcd" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-etcd" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-flannel" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-flannel" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-flannel" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-k8s-metrics-server" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-k8s-metrics-server" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-k8s-metrics-server" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-kubernetes" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-kubernetes" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-kubernetes" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-kubernetes" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-kubernetes" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-kubernetes" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-kubernetes" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-kubernetes" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-node-feature-discovery" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-whereabouts" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/hardened-whereabouts" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/helm-project-operator" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/jimmidyson-configmap-reload" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/k3s-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/k3s-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/k3s-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/k3s-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/k3s-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/k3s-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/k3s-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/k3s-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/klipper-helm" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/klipper-helm" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/klipper-helm" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/klipper-lb" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/klipper-lb" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/kube-api-auth" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/kubectl" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/kubectl" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/kubectl" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/kubectl" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/kubectl" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/kubectl" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/library-nginx" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/local-path-provisioner" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/local-path-provisioner" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/machine" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/nginx-ingress-controller" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/nginx-ingress-controller" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/nginx-ingress-controller" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/nginx-ingress-controller" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/pause" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/prom-alertmanager" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/prom-node-exporter" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/prom-prometheus" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/prometheus-auth" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/prometheus-auth" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/prometheus-federator" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/pushprox-client" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/pushprox-proxy" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rancher-agent" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rancher-csp-adapter" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rancher-runtime" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rancher-webhook" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rancher" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke-tools" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-cloud-provider" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-cloud-provider" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-runtime" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-runtime" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-runtime" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-runtime" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-runtime" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-runtime" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-runtime" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-runtime" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/rke2-upgrade" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/security-scan" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/shell" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-k3s" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent-installer-rke2" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-agent" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/system-upgrade-controller" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/ui-plugin-operator" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/webhook-receiver" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "rancher/webhook-receiver" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "quay.io/jetstack/cert-manager-cainjector" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "quay.io/jetstack/cert-manager-controller" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "quay.io/jetstack/cert-manager-webhook" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "quay.io/jetstack/cert-manager-ctl" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/csi-attacher" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/csi-provisioner" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/csi-resizer" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/csi-snapshotter" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/csi-node-driver-registrar" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/livenessprobe" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/backing-image-manager" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/longhorn-engine" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/longhorn-instance-manager" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/longhorn-manager" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/longhorn-share-manager" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/longhorn-ui" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "longhornio/support-bundle-kit" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "docker.io/neuvector/enforcer" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "docker.io/neuvector/controller" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "docker.io/neuvector/manager" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "docker.io/neuvector/scanner" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
    "docker.io/neuvector/updater" = { image_tag_mutability = "MUTABLE", scan_on_push = false, expiration_after_days = 1, force_delete = true }, 
  }
}

module "ecr" {
  source   = "./modules/ecr"
  for_each = local.repositories

  name                  = each.key
  image_tag_mutability  = each.value.image_tag_mutability
  scan_on_push          = each.value.scan_on_push
  expiration_after_days = each.value.expiration_after_days
  force_delete          = each.value.force_delete

}