apiVersion: management.cattle.io/v3
customized: false
default: '{}'
kind: Setting
metadata:
  name: ui-banners
value: '{"loginError":{"message":"","showMessage":"false"},"bannerHeader":{"background":"#007a33","color":"#ffffff","textAlignment":"center","fontSize":"14px","text":"UNCLASSIFIED"},"bannerFooter":{"background":"#007a33","color":"#ffffff","textAlignment":"center","fontSize":"14px","text":"UNCLASSIFIED"},"bannerConsent":{"background":"#eeeff4","color":"#141419","button":"Accept","html":"<div
  style=\"font-size:24px;line-height:2.0;text-align:center;\">\n  <p style=\"margin:0
  0 12px 0;\"><strong>DoD Warning and Consent Banner</strong></p>\n</div>\n<div style=\"font-size:14px;line-height:1.6;text-align:center;\">\n  <p
  style=\"margin:0 0 12px 0;\"><strong>You are accessing a U.S. Government (USG) Information
  System (IS) that is provided for USG-authorized use only. By using this IS (which
  includes any device attached to this IS), you consent to the following conditions:</strong></p>\n  <p
  style=\"margin:0 0 12px 0;\">The USG routinely intercepts and monitors communications
  on this IS for purposes including, but not limited to, penetration testing, COMSEC
  monitoring, network operations and defense, personnel misconduct (PM), law enforcement
  (LE), and counterintelligence (CI) investigations.</p>\n  <p style=\"margin:0 0
  12px 0;\">At any time, the USG may inspect and seize data stored on this IS.</p>\n  <p
  style=\"margin:0 0 12px 0;\">Communications using, or data stored on, this IS are
  not private, are subject to routine monitoring, interception, and search, and may
  be disclosed or used for any USG authorized purpose.</p>\n  <p style=\"margin:0
  0 12px 0;\">This IS includes security measures (e.g., authentication and access
  controls) to protect USG interests--not for your personal benefit or privacy.</p>\n  <p
  style=\"margin:0 0 12px 0;\">Notwithstanding the above, using this IS does not constitute
  consent to PM, LE or CI investigative searching or monitoring of the content of
  privileged communications, or work product, related to personal representation or
  services by attorneys, psychotherapists, or clergy, and their assistants. Such communications
  and work product are private and confidential.</p>\n  <p style=\"margin:0 0 12px
  0;\">See User Agreement for details.</p>\n</div>"},"showHeader":"true","showFooter":"true","showConsent":"true"}'
